export const SET_SELECTED_CATEGORY = "SET_SELECTED_CATEGORY";
export const SET_SELECTED_LEVEL = "SET_SELECTED_LEVEL";
export const SET_SELECTED_TYPE = "SET_SELECTED_TYPE";
export const SET_QUESTION_COUNT = "SET_QUESTION_COUNT";